### ISSUE TITLE
Cannot load TIFFs

### ISSUE THREAD

**Issue by akidee** [image-js/image-js#508]
node v12.13.0

Example:

`Image.load(TIFF).then(function (image) {
  console.log('Width', image.width);
}).catch(e => console.log(e));`

Result:

`RangeError: incorrect data size: 36578304. Should be 12192768
    at new Image (/Users/andi/.node_libraries/tifftest/node_modules/image-js/lib/image/Image.js:249:15)
    at getImageFromIFD (/Users/andi/.node_libraries/tifftest/node_modules/image-js/lib/image/core/load.js:223:12)
    at loadTIFF (/Users/andi/.node_libraries/tifftest/node_modules/image-js/lib/image/core/load.js:178:12)
    at loadBinary (/Users/andi/.node_libraries/tifftest/node_modules/image-js/lib/image/core/load.js:67:16)`

Neither 8 or 16 bit TIFFs can be loaded.

**Comment by targos** [comment]
Support for RGB TIFF was added last week. Can you try with the latest version (0.23.3) ?
