### ISSUE TITLE
Error when loading image: "DOMImage requires the canvas library."

### ISSUE THREAD

**Issue by eh-dub** [image-js/image-js#527]
I am using `image-js` 0.30. I was having no issues loading images but then I started getting the following error:
`Error: DOMImage requires the canvas library. Install it with npm install canvas@next.`

Here's the full stack trace:
```
(node:8746) UnhandledPromiseRejectionWarning: Error: DOMImage requires the canvas library. Install it with `npm install canvas@next`.
    at new DOMImage (app/node_modules/image-js/lib/image/core/environment.js:41:11)
    at app/node_modules/image-js/lib/image/core/load.js:242:17
    at new Promise (<anonymous>)
    at loadGeneric (app/node_modules/image-js/lib/image/core/load.js:241:10)
    at loadBinary (app/node_modules/image-js/lib/image/core/load.js:74:10)
    at app/node_modules/image-js/lib/image/core/load.js:97:12
    at async Promise.all (index 0)
    at async app/main/image.js:19:25
    at async Promise.all (index 0)
    at async Object.averageFrames [as default] (app/main/image.js:12:27)
```

I have already run `yarn add canvas@next` to no avail.

**Comment by eh-dub** [comment]
I was accidentally feeding a `.DS_Store` file into the stack.
