### ISSUE TITLE
[support] TypeError: img1.subtractImage is not a function

### ISSUE THREAD

**Issue by santosh** [image-js/image-js#541]
My code:

```javascript
const { Image } = require("image-js");

const img1 = Image.load("img1.jpg");
const img2 = Image.load("img2.jpg");

const diff = img1.subtractImage(img2, {});

diff.save("diff.jpg");
```

The error:

```
C:\Users\Santosh Kumar\Desktop\imgdiff\imagejs.js:6
const diff = img1.subtractImage(img2, {});
                  ^
                  ^

TypeError: img1.subtractImage is not a function
    at Object.<anonymous> (C:\Users\Santosh Kumar\Desktop\imgdiff\imagejs.js:6:19)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47
```

**Comment by targos** [comment]
`Image.load` is asynchronous and returns a Promise. You have to execute your code in an async function and `await Image.load()`

**Comment by santosh** [comment]
Thanks @targos
